from fpdf import FPDF
import io

class LegalPDF(FPDF):
    """Custom PDF class for professional legal reporting."""
    def header(self):
        # Professional Heading
        self.set_font('Arial', 'B', 16)
        self.set_text_color(44, 62, 80)  # Professional Deep Blue
        self.cell(0, 15, 'CONTRACT RISK ASSESSMENT REPORT', 0, 1, 'C')
        self.set_draw_color(241, 196, 15) # Gold underline
        self.line(10, 25, 200, 25)
        self.ln(10)

    def footer(self):
        # Page numbers
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Contract Insight AI', 0, 0, 'C')

def generate_pdf_report(filename, overall_risk, results):
    """Generates a professional PDF document of the analysis results."""
    pdf = LegalPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # Metadata Section
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(40, 10, "Document Name: ", 0, 0)
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, filename, 0, 1)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(40, 10, "Risk Status: ", 0, 0)
    
    # Color code the overall risk in PDF
    if overall_risk == "CRITICAL":
        pdf.set_text_color(231, 76, 60) # Red
    elif overall_risk == "MODERATE":
        pdf.set_text_color(243, 156, 18) # Orange
    else:
        pdf.set_text_color(39, 174, 96) # Green
        
    pdf.cell(0, 10, overall_risk, 0, 1)
    pdf.set_text_color(0, 0, 0) # Reset to black
    pdf.ln(10)

    # Detailed Clause Section
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Detailed Clause Analysis", ln=True)
    pdf.ln(5)

    for row in results:
        # Clause ID and Risk Level
        pdf.set_font("Arial", 'B', 11)
        pdf.set_fill_color(245, 247, 250)
        pdf.cell(0, 10, f" Clause {row['id']} - Risk: {row['risk']}", 1, 1, 'L', fill=True)
        
        # Explanation and Suggestion with wrapping text
        pdf.set_font("Arial", size=10)
        
        # Multi-cell handles long Hindi and English text correctly
        # Encoding to latin-1 replaces unsupported Unicode chars with '?' to prevent crashes
        clean_exp = row['explanation'].encode('latin-1', 'replace').decode('latin-1')
        clean_sug = row['suggestion'].encode('latin-1', 'replace').decode('latin-1')
        
        pdf.multi_cell(0, 8, f"Explanation: {clean_exp}", border='LR')
        pdf.multi_cell(0, 8, f"Suggestion: {clean_sug}", border='LRB')
        pdf.ln(5)
        
    # Return as bytes
    return pdf.output(dest='S').encode('latin-1')

def generate_txt_report(filename, overall_risk, results):
    """Generates a plain text report for maximum compatibility."""
    report = f"CONTRACT RISK AUDIT REPORT\n"
    report += "="*40 + "\n"
    report += f"FILE: {filename}\n"
    report += f"OVERALL STATUS: {overall_risk}\n"
    report += "="*40 + "\n\n"
    
    for row in results:
        report += f"[{row['id']}] RISK LEVEL: {row['risk']}\n"
        report += f"EXPLANATION: {row['explanation']}\n"
        report += f"SUGGESTION: {row['suggestion']}\n"
        report += "-"*20 + "\n\n"
        
    return report